= Pure Functions


A pure function is a function that

. _always_ returns the same values for the same arguments
. and which _only_ produces results via its return value.

The first condition means that every value that is used by the function to produce a result must be passed as arguments. This means that a pure function is forbidden from:

* Reading from the console
* Reading from a file
* Reading from a database
* Reading environmental variables
* Fetching data via a network request
* Reading a global variable

For example, the following pure function can always run given the listed arguments, and always has the same result:

[source,typescript]
----
const scale = (value: number) => 2
----

However, the following function is not pure, because it generates a random value with the help of its environment, which means that it can return different values for the same arguments:

[source,typescript]
----
const randomdigit = () => Math.floor(10 * Math.random())
----

The second condition means that the function must return all results via its return value. Results that are not returned are called _side effects_, and are forbidden; some examples are:

* Writing to the console
* Writing to a file
* Writing to a database
* Making a network request
* Throwing an error
* Mutating a global variable

For example, the following function is _not_ pure, because it writes to the console:

[source,typescript]
----
const greet = (name: string) => {
  console.log(`Hello, ${name}!`)
}
----

And this function sends a network request, which is also forbidden:

[source,typescript]
----
const saveUser = (user: User) => {
  fetch('https://api.example.com/users', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(user),
  })
}
----

But how does a pure function represent side effects? How can it produce a network request if it's not allowed to call `fetch()`? The workaround is to produce a value that represents an instruction for the calling environment to produce the side effect. For example, instead of calling `fetch()`, a pure function could return an object that represents a network request:

[source,typescript]
----
type NetworkRequest = {
  url: string
  method: 'GET'
  headers: Record<string, string>
} | {
  url: string
  method: 'POST'
  headers: Record<string, string>
  body: string
}
const saveUser = (user: User): NetworkRequest => {
  return {
    url: 'https://api.example.com/users',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(user),
  }
}
----

It would be up to the calling environment to interpret the `NetworkRequest` object and produce the side effect:

[source,typescript]
----
const request = saveUser(user)
fetch(request.url, {
  method: request.method,
  headers: request.headers,
  body: request.body,
})
----

This might seem like a lot of work for nothing—we just moved the request out from `saveUser` and added a whole lot of boilerplate—but this detour will reward us in the long run. One of the consequences of adhering to the two constraints of purity is that the type signature will embed.

1. _All_ requirements for executing the function—in the arguments.
2. _All_ possible results—including side effects—in its return type.

This makes the code _much_ easier to test. Test are very important to ensure that the code is correct, and the first step to better test coverage is to make the code _testable_.

* Because all the information needed to run the function is in the argument types, there is no need to mock the environment (set up a database, mock network responses, etc).
* Because all results are embedded in the return type, there is no need to check the environment after the function has run.
* Because you only need to provide inputs (arguments) and check the output (return value), it's super easy to write tests. You will end up with a much more well-tested codebase.
* Because the function always produces the same results for the same input, the tests are deterministic and can be parallelized. Say goodbye to flaky tests!

Static code analysis tools such as TypeScript's type checker and `@typescript-eslint` helps to make certain guarantees for how the code behaves at runtime. The more you utilize the type system, the more these tools can help you. By writing pure functions, you are leveraging the type system to its fullest extent.