= TypeScript Foundations
Johannes Lindgren
:imagesdir: images
:toc:

This is a quick introduction to TypeScript for programmers who are already familiar with JavaScript. We'll look at the fundamental building blocks with which we can model most of our programs:

- union Types (sum types)
- tuples, arrays, records (product types)
- function types (exponential types)
- generic types (parametric types)

However, before delving deep into TypeScript's syntax, let's first explore what motivates us to adopt TypeScript in the first place, and how TypeScript relates to JavaScript.

== What is TypeScript?

The main reason to adopt TypeScript is to get guarantees of code behaves at runtime at compile-time. Specifically, TypeScript helps you to prevent code from crashing. It is preferrable to give the programmer an error in the IDE than to let the client experience an incident in production. Sadly, in nature, nothing is for free; to get something, you first have to give up something else. While TypeScript gives you guarantees of how the code behaves at runtime, it forced the programmer to write in a more limited way. This is not a unique trait to TypeScript, but programming languages have been following this trend ever since the advent of computing:

- Programming started with raw machine code and Assembly languages that directly translates to machine code. Assembly languages are notoriously difficult to reason about. Therefore, more restrictive languages soon emerged.
- Procedural languages, such as Fortran, contrains the programmer to deal with variables, rather than registers and memory addresses.
- Structured languages prohibits you from using `goto` statements in favor of conditional blocks, loops, and subroutines; which guarantees that the program follows the control flow. For example, in high-level languages like C, you use `if` and `for` statements, rather than `goto`.
- Garbage-collected languages prohibits you from allocating and freeing up memory directly, but in return (to some degree) guarantees no memory leaks.
- Pure functional languages prohibits you from mutating values, which guarantees that the program can be run concurrently.
- Pure functional languages prohibits you from making side effects, which guarantees that function calls can be cached.

With every new paradigm on this list, the programmer is more and more limited in what machine-code they are able to produce; but in return, they are better able to write bug-free code. TypeScript is no different in that it adds new constraints to JavaScript; it prohibits you from using data in _potentially_ incorrect ways, which guarantees that you don't run into runtime exceptions. TypeScript limits what code you'd otherwise be allowed to write in JavaScript, but in turn gives you certain guarantees of how your program behaves at runtime. You're trading freedom against:

- Fewer runtime errors
- Improved refactoring
- Documententation for your modules

=== A Language or a Linter?

TypeScript may have started out as a compiled programming language, adding new capabilities to JavaScript such as classes. But as JavaScript incrementally adopted these features, TypeScript today is more often used as a linter that checks your code for potential errors.

ESLint can eliminate code such as this:

[source,javascript]
----
var a = 0
if(a == ''){
  console.log('zero equals empty string')
}
----

In favor of this:

[source,javascript]
----
const a = 0
if(a === ''){
  console.log('zero equals empty string')
}
----

TypeScript can analyze the code at a deeper level and understand that the log statment will never execute. Furthermore, it can understand when code will result in runtime errors:

[source,javascript]
----
// Valid JavaScript, but invalid TypeScript
const double = (value) => value * 2
let b = double('twelve')
----

Though TypeScript can only give false errors: some programs have valid syntax, no runtime error, yet not pass the type checker:

[source,javascript]
----
// Valid JavaScript with no runtime errors, yet invalid TypeScript
const double = (value) => value * 2 // <- TypeScript cannot infer the type of `value`
const pi = 3.14
const tau = double(pi)
----

If TypeScript cannot guarantee that the code is correct, it will give an error, forcing you to refactor your program.

TypeScript lets us annotate JavaScript with _type annotations_. The example above can be made to to work by annotating the `value` parameter:

[source,javascript]
----
// Valid JavaScript AND TypeScrip
const double = (value: number) => value * 2
const pi = 3.14
const tau = double(pi)
----

Though as of today (2023), this code cannot run in the browser. Therefore, `.ts` files are compiled into `.js` files simply by eliminating the type annotations. Code such as this:

[source,javascript]
----
const double = (value: number) => value * 2
----

gets transformed into this:

[source,javascript]
----
const double = (value) => value * 2
----

In this sense, we can understand TypeScript more as a powerful linter, rather than an entirely different programming language.

With the constraints in mind, we can also understand TypeScript as _subset_ of JavaScript. While some claim TypeScript to be a _superset_ of JavaScript, I'd argue otherwise. If anything, I think it is _JavaScript_ that is a superset of TypeScript. Consider all JavaScript and TypeScript programs there is: if you take a random JavaScript program sample, there is only a slim chance that it passes the checks by TypeScript. But take (almost) any TypeScript program, strip away the type annotation, and you'd have a valid JavaScript program. In this sense, TypeScrip is a _subset_ of JavaScript.

== Types

In JavaScript we deal exclusively with values:

[source,javascript]
----
const age = 42
----

A value is something that can be stored in memory while the program is running. The identifiers of variables start with lowercase.

In TypeScript we also consider the _set of values_ that our variables can reference; this is called a _type_. A type is like a set in that it consistes of a collection values. The identifiers of types start with uppercase. For example, we could construct a set `Digit` that contains the numbers 0–9:

image:Digit.svg[]

We can now annotate a value `digit` with the type `Digit` to tell TypeScript that whatever value is in `digit`, it must be one of the values in `Digit`:

[source,typescript]
----
const digit: Digit = 5
----

If you assign a value that is not in the annotated type, TypeScript will generate compile-time error:

[source,typescript]
----
const digit: Digit = 10
----

Note that you can still run the program. This is because when TypeScript code is compiled, all type annotations are removed. This is what the compiled output looks like:

[source,js]
----
const digit = 10
----

== Primitive Types

We're going to explore the various types in TypeScript, starting with the most primitive types, and then moving on to more complex, composite types.

=== Literal/value types

The most primitive kind of type is a type literal:

[source,typescript]
----
const nothing: undefined = undefined
----

This just tells us that `nothing` can only ever have one value: `undefined`. Note that the occurrence of `undefined` between the `:` and `=` symbols is actually a type and not a value. For each literal value, there exists a corresponding type with the same name.

> For each literal value, there exists a corresponding type with the same name.

So the symbols `undefined`, `true`, `false`, `123`, `"hello"` can be either values or types depending on where in the syntax tree they appear. For example, if a literal appears directly after an assigment operator (`=`), it is a value; but if it appears after the colons (`:`) after a variable declaration, it is a type.

image:primitive-types.svg[]

=== Sum/Union Types

Value types are not very interesting on their own--they get much more interesting when they're combined into larger types. Consider the two types `true` and `false`:

image:true-and-false.svg[]

Like other strongly typed functional programming languages, TypeScript has _type operators_ that let you combine types in different ways. One of these operators is the _type union operator_ `|`, which lets you combine two types into a new types that contains all values from both operands:

image:boolean.svg[]

In TypeScript, this can be written as such:

[source,typescript]
----
const amIHappy: true | false = true
----

The expression `true | false` can be read as "true or false", and is only evaluated at compile-time by the type checker.

`true | false` is such a common occurrence that TypeScript has a built-in type for it; called `boolean`:

[source,typescript]
----
const amIHappy: boolean = true
----

NOTE: `boolean` is a primitive type. All primitive types are always written in lowercase.

=== Type Aliases (`type`)

A type expression is an expression that evaluates to a type, such as:

[source,typescript]
----
true | false
----

In TypeScript, you can alias such expressions with _type aliases_:

[source,typescript]
----
type TrueOrFalse = false | true
----

`TrueOrFalse` becomes a type that contains the values `false` and `true`, and can be used as any other type:

[source,typescript]
----
const amIHappy: TrueOrFalse = true
----

Since `TrueOrFalse` contains the exact same number of values as `boolean`, these two types are equivalent to each other--they're just different names for the same type. You can view the `boolean` type as being a type alias for `true | false`:

[source,typescript]
----
// Pseudo code
type boolean = false | true
----

NOTE: Type aliases are always written in _PascalCase_.

=== `number`

You could create a `Digit` type that contains the numbers 0–9:

[source,typescript]
----
type Digit = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
----

Then _imagine_ that you could extend this to all JavaScript numbers:

[source,typescript]
----
// Pseudo code
type NaturalNumbers = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | ...
type Integer = ... | -10 | -9 | -8 | -7 | -6 | -5 | -4 | -3 | -2 | -1 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | ...
type FloatingPointNumbers = ... | 0 | ... | 0.0000000000001 | ... | 0.0000000000002 | ...
----

Then you could think of the `number` type as being defined as the type that contains all integers, floating point numbers, `Infinity`, `-Infinity`, and `NaN`.

[source,typescript]
----
// Pseudo code
type number = Integer | FloatingPointNumbers | Infinity | -Infinity | NaN
----

This is the `number` type.

=== `string`

The `string` type contains all strings, and you can think of it in similar terms as the `number` type:

[source,typescript]
----
// Pseudo code
type string = 'a' | 'b' | 'c' | ... | 'z' | 'aa' | 'ab' | 'ac' | ... | 'az' | 'ba' | 'bb' | 'bc' | ... | 'zz' | 'aaa' | 'aab' | ...
----

Again, this is just pseudo code. In reality, the `number` and `string` types are built-in types in TypeScript, and you cannot redefine them.

=== `null` and `undefined`

The `null` and `undefined` types are the types that contain the values `null` and `undefined`, respectively:

[source,typescript]
----
const nothing: null = null
const notDefined: undefined = undefined
----

As with any literal type, they are most useful when combined with other types:

[source,typescript]
----
type MaybeNumber = number | undefined
const maybeNumber: MaybeNumber = 42
const maybeNot: MaybeNumber = undefined
----

TIP: whenever you have a choice, prefer to use `undefined` over `null`. `undefined` is a more consistently used in Node.js and DOM APIs, is the result when indexing out of bounds, and is the default value for uninitialized variables.

=== `Symbol` and `bigint`

Finally, you have the primitive data types `bigint` that is the type that contains all https://developer.mozilla.org/en-US/docs/Glossary/BigInt[BigInts], and `symbol` that contains all https://developer.mozilla.org/en-US/docs/Glossary/Symbol[Symbols].

== Type Inference

So far in our code examples, we have annotated every single identifier with a type:

[source,typescript]
----
const age: number = 21
const ageAsString: string = age.toString()
----

But if you think for a second about this code, you can easily deduct that the program is correct:

1. `age` is assigned the value `21`, thus `age` must be of type `number`.
2. Since `age` is a number, you can call age.toString()`, which evaluates to a value of type `string`.
3. Therefore, `ageAsString` must be of type `string`

TypeScript is able to perform the same line of reasoning, which means that you can omit the type annotations without getting any type errors:

[source,typescript]
----
const age = 21
const ageAsString = age.toString()
----

This looks just like JavaScript, and is in fact also a valid TypeScript program. This ability of TypeScript to deduct the type of variables is called _type inferrence_.

1. On the first line, TypeScript infers that the value of `age` is `number`.
2. On the second line, TypeScript infers that the type of `age.toString()` is `string`.
3. Lastly, TypeScript infers that the type of `ageAsString` is `string`.

Why then do we need type annotations? The answer is that when the type cannot be inferred by its usage. For example, in the following code, TypeScript cannot infer the type of `value`:

[source,typescript]
----
const twice = (value: number) => 2 * value
----

The first argument in the `twice` function is annotated with the type `number`, so that TypeScript can guarantee that whatever goes into the multiplication is a number. More on <<_functions, functions later>>.

=== Type Inference of Primitive Values

When you assign a value to a variable, TypeScript infers the type of the variable based on the type of the assigned value. In the example below, `thomas` is of type `User`. When the variable `user` is assigned `thomas`, the type inferred type is also `User`:

.The type of `user` is inferred as `User`
[source, typescript]
----
const thomas: User = ...
const user = thomas
----

Unfortunately, there is one inconsistency in the type inference mechanism: TypeScript does not infer the type of value literals as the corresponding type literal; in the example below, the variable `pi` is inferred as `number`, not `3.14159`:

.The type of `pi` is inferred as `number`
[source,typescript]
----
const pi = 3.14159
----

Here's how TypeScript infers primitive values:

* numbers (`1`, `0.5`, `NaN`, `100`) are inferred as `number`
* strings (`'hello'`, `"world"`) are inferred as `string`
* booleans (`true`, `false`) are inferred as `boolean`
* `undefined` is inferred as `undefined`
* `null` is inferred as `null`
* `Symbol` is inferred as `symbol`
* `bigint` is inferred as `bigint`

To infer it as the literal type, you can annotate the use a _type assertion_:

.The type of `pi` is inferred as `3.14159`
[source,typescript]
----
const pi = 3.14159 as 3.14159
----

== The `unknown` type

The `unknown` type contains all types, including the types we haven't yet covered:

[source,typescript]
----
// Pseudo code
type unknown = boolean | number | string | null | undefined...
----

If an identifier is typed with `unknown`, TypeScript can't infer any information from it, because it can be assigned any value:

[source,typescript]
----
const a: unknown = 123
const b: unknown = { a: 'a' }
const c: unknown = () => 123
----

You may encounter the `any` type at some point. `any` is the same type as `unknown`, but it also _disables the type checker_. Never ever use it. If you really want to work around the type system, it's better to be explicit.

WARNING: The `any` type disables the type checker--never use it!

== Tuples(product types)

While unions describe types of that are either "this _or_ that", tuples describes types that embed "this _and_ that".

Tuples are arrays of fixed size, and are annotated with square brackets `[]`. The simplest tuple does not contain any data:

[source,typescript]
----
type Unit = []
const unit = []
----

It gets more interesting as we embed information in the tuple types:

[source,typescript]
----
type LineCoordinate = [number]
const x = [10]
type PlaneCoordinate = [number, number]
const planeCoordinate = [10, 45]
type SpaceCoordinate = [number, number, number]
const spaceCoordinate = [10, 45, -125]
----

Because TypeScript knows how many elements the tuple contain, we can destructure them:

[source,typescript]
----
const [x, y, z] = spaceCoordinate
----

Tuples are sometimes useful when we want to return two or three results from a function. Instead of using parameters as out parameters (as done in languages such as Java), or returning object with names properties, return a tuple. In the following example, TypeScript can infer that `Promise.all` returns a promise of `[string, number, Date]`, because the argument was a tuple:

[source,typescript]
----
const [name, age, startDate] = await Promise.all([
    Promise.resolve('Eamonn'),
    Promise.resolve(21),
    Promise.resolve(new Date(2012, 9, 1)),
]);
----

== Arrays

Combining With tuples and union types, we can create arrays of limited length:

[source,typescript]
----
type UpToTwoNumbers = [] | [number] | [number, number]
----

This array can have 0, 1, or 2 elements. This is not a common use case, but consider instead what happens when we expand the series to infinity:

[source,typescript]
----
// Pseudo code
type number[] = []
  | [number]
  | [number, number]
  | [number, number, number]
  | [number, number, number, number]
  | ...
----

This gives us an array of any length. While the above example is just pseudo code, some languages do in fact define arrays like this.

We can create arrays of different types:

[source,typescript]
----
const numbers: number[] = [1, 2, 3, 4, 5, 6, 7, 8]
const booleans: boolean[] = [false, true, false]
----

== Object types/Records (product types)

Tuples and arrays lets us encode multiple types into a new type. For example, we could encode a person's name and age in a tuple:

[source,typescript]
----
type Person = [
  // name
  string,
  // age
  number,
]
----

The problem is that as more items are added to the tuple, it gets more difficult to keep track of which index correspond to which property. Consider what happens if we also include the person's height, the birth year in `Person`: Can you easily tell which index contains the height and which contains the birth year?

[source,typescript]
----
type Person = [
  string,
  number,
  number,
  number,
]
----

A _record_ (also known as _object_) allows us to label each item:

[source,typescript]
----
type Person = {
  name: string
  age: string
  height: number
  birthYear: number
}
----

which lets us instantiate an object as

[source,typescript]
----
const person = {
  name: 'Johannes Kepler',
  age: 58,
  height: 1.76,
  birthYear: 1571,
}
----

By aligning these two types side-by-side, you can easily see that these two structures are mathematically identical, because they contain the same amount of information, but the record/object is more ergonomic:

[source,typescript]
----
type Person = [
  string,
  number,
  number,
  number,
]
type Person = {
  name: string
  age: string
  height: number
  birthYear: number
}
----

In statically typed programming languages such as C++, the property names of records (classes) do not exist at runtime; in memory, the records are stored as arrays.

== Optional Properties

Sometimes, we want to allow properties to be optional:

[source,typescript]
----
// Optional
type GeoCoordinateImplicit = {
  latitude: number
  longitude: number
  elevation?: number
}
const k2Peak: GeoCoordinateExplicit = {
  latitude: 35.8825,
  longitude: 76.513333,
  elevation: 8611,
}
const mountEverestPeak: GeoCoordinateImplicit = {
  latitude: 27.988056,
  longitude: 86.925278,
}
----

However, when possible, it's best to be explicit by the property as a union with `undefined`:

[source,typescript]
----
type GeoCoordinateExplicit = {
  latitude: number
  longitude: number
  elevation: number | undefined
}

const k2Peak: GeoCoordinateExplicit = {
  latitude: 35.8825,
  longitude: 76.513333,
  elevation: 8611,
}
const mountEverestPeak: GeoCoordinateImplicit = {
  latitude: 27.988056,
  longitude: 86.925278,
  elevation: undefined
}
----

This forces the API consumer to consciously set the property to `undefined`.

Just note that these are not identical:

[source,typescript]
----
// A != B
type A = {
  prop?: number
}
type B = {
  prop: number | undefined
}
// correct
const a: A = {}
const a: A = { prop: 1 }
const b: A = { prop: 1}
// incorrect
const b: A = {}
----

== Type Guards

Consider a type that is a union between two smaller types; for example `number | undefined`:

image:type-guard.diagrams.svg[]

If you want to use the value as a number, you first need to check that it' not `undefined` before you can use it. This is called a _type guard_.

[source,typescript]
----
const value: number | undefined = ...
if(value !== undefined) {
  console.log('Twice', value * 2)
}
----

TypeScript understands that if the conditional statement gets executed, `value` cannot be `undefined`, and can therefore be used as a number: TypeScript has _narrowed down_ the type from `number | undefined` to `number`.

=== Non-null and non-undefined type guards

A nullable or optional value has a type that is a union with `null` or `undefined`; for example, `string | null` and `number | undefined`. You can perform checks for `null` and `undefined` with the `!==` and `===` operators, respectively:

[source,typescript]
----
const nullable: string | null = ...
const optional: string | undefined = ...
if(nullable !== null) {
  console.log('Not null', nullable)
}
if(optional !== null) {
  console.log('Defined', optional)
}
----

=== The `typeof` type guard

If you have a union between other types, for example, `string | number`, or `unknown`, use the `typeof` operator to check the type at runtime:

[source,typescript]
----
const value: unknown = ...
if(typeof value === 'number') {
  console.log('Double the value', value * 2)
}
----

If `typeof value === 'number'` is true, TypeScript infers that the type of `value` is `number` _inside the conditional block_. This allows the use of `value` in the arithmetical expression.

This is how TypeScript infers the type based on the string in the `typeof === ` expression:

- `typeof x === 'undefined'` infers the type of `x` as `undefined`
- `typeof x === 'null'` infers the type of `x` as `object`.
- `typeof x === 'number'` infers the type of `x` as `number`
- `typeof x === 'string'` infers the type of `x` as `string`
- `typeof x === 'boolean'` infers the type of `x` as `boolean`
- `typeof x === 'symbol'` infers the type of `x` as `symbol`
- `typeof x === 'bigint'` infers the type of `x` as `bigint`

NOTE: `typeof x === 'object'` infers the type of `x` as `object | null` because `typeof null === 'object'` is true. This is due to a https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#typeof_null[historical mistake] in the JavaScript language design, and is not something that TypeScript can fix.

Non-primitive values are inferred as:

- `typeof x === 'function'` infers the type of `x` as `function`
- `typeof x === 'object'` infers the type of `x` as `object | null`

=== Validating Objects (`in`)

If the `typeof` operator returns `object`, you also need to check that the value is not `null`:

[source,typescript]
----
const obj: unknown = ...
if(typeof obj === 'object' && obj !== null) {
  console.log('The type is `object`')
}
----

If the type of a value is `object`, you can use the `in` operator to check whether a property on that object exists:

[source,typescript]
----
const val: unknown = ...
if(typeof val === 'object' && val !== null && 'id' in val) {
  console.log('The type is `{ id: unknown}`')
}
----

Finally, given all of these checks, you can safely check the type of the property:

[source,typescript]
----
const val: unknown = ...
if(typeof val === 'object' && val !== null && 'id' in val && typeof val.id === 'number') {
  console.log('The type is `{ id: number }`')
}
----

=== The optional chaining operator

If you have a deeply nested object with optional properties, it gets verbose to check for `undefined` values with the equality operator (`===`). Use the _optional chaining operator_ (`?.`) to check whether a property exists:

[source,typescript]
----
const obj: { prop?: number }
console.log(obj.prop?.toFixed(2))
----

The optional chaining operator is a shorthand for the following:

[source,typescript]
----
const obj: { prop?: number }
console.log(obj.prop === undefined ? undefined : obj.prop.toFixed(2))
----

=== The `instanceof` Operator

If you use the `instanceof` operator, TypeScript infers the type of the value as the type on the right side of the operator:

[source,typescript]
----
const value: unknown = ...
if(value instanceof Date) {
  console.log('The type is `Date`')
}
----

=== `Array.isArray()`

You can use the `Array.isArray()` function to check whether a value is an array:

[source,typescript]
----
window.addEventListener('message', (event) => {
  if(Array.isArray(event.data)) {
    console.log('The type is `unknown[]`')
  }
})
----

This is preferred over `instanceof Array` which doesn't work across windows and frames.

=== User Defined Type Guards (Type Predicates)

We saw that validation of objects generates a lot of boilerplate code. You could extract the code like this

[source,typescript]
----
type Entity = {
  id: number
}
function isEntity(value: unknown): boolean {
  return typeof value === 'object' && value !== null && 'id' in value && typeof value.id === 'number'
}
----

However, if you use this in an if-statement, TypeScript can no longer infer the type of the value:

[source,typescript]
----
const value: unknown = ...
if(isEntity(value)) {
  console.log('Id', value.id) // <-- Type Error, since 'id` doesn't exist on `unknown`
}
----

The reason is that the type signature of `isEntity` reveals nothing about the type guard. You can include a _user-defined type guard_ to fix this:

[source,typescript]
----
type Entity = {
  id: number
}
function isEntity(value: unknown): value is Entity {
  return typeof value === 'object' && value !== null && 'id' in value && typeof value.id === 'number'
}
----

This function still returns a boolean, but if the return value is `true`, TypeScript infers that the type of `value` is `Entity`. The expression `value is Entity` is called a _type predicate_.

CAUTION: The type predicate does not need to match the inferred type in the function body: TypeScript will simply trust that the predicate is accurate. In the example above, we could have written `value is null`, and TypeScript wouldn't have generated an error. So whenever you create a user-defined type guard, include unit tests to ensure that the type guard is accurate.

=== Discriminated/tagged unions & Pattern Matching

Object types, combined with unions lets us define discriminated unions (aka tagged unions).

For example, consider the case when we want to represent the outcome of a calculation:

1. Success
2. Failure

We _could_ represent this with a single structure with optional properties.

[source,typescript]
----
type Result = {
  data?: string
  error?: Error
}
----

And represent a result like this

[source,typescript]
----
const ok: Result = {
  data: 'Hello!'
}
const error: Result = {
  error: new Error('arg!')
}
----

But what would the following data represent?

[source,typescript]
----
const what: Result = {
  data: 'success!',
  error: Error('... and also failure?!')
}
const ehmm: Result = {}
----

With discriminated unions, we can define an API that _only can represent valid states_:

[source,typescript]
----
type Success = {
  tag: 'success'
  data: string
}

type Failure = {
  tag: 'failure'
  error: Error
}

type Result = Ok | Err

// Correct
const ok: Result = {
  tag: "success",
  data: 'Hello!'
}
const fail: Result = {
  tag: 'failure',
  error: new Error('Crash! Boom! Bang!')
}
----

As you can see, the `tag` property determines whether the `data` or the `error` properties are defined; there is no way both of these properties can be present or absent at the same time.

By using a switch statement on the `tag` property, TypeScript is able to infer the types of the other properties in the `case` blocks:

[source,typescript]
----
const res = ok as Result
switch (res.tag) {
  case "success":
    console.log('We won: ', res.data)
    break
  case "failure":
    console.log('We disappointed...', res.error)
}
----

This is called _pattern matching_.

== Type Assertions

You will encounter scenarios where you want to initialize a value to `undefined`, but later reassign it to a different value:

[source,typescript]
----
let user: undefined | User = undefined

// Later...
user = await fetchUser() // Returns a `User`
----

In this case, you must annotate `user` with a type `undefined | User`.

However, in some scenarios where you deal with records, you may have situation where you'd rather use the type inference to its greatest extent; for example, consider a state-like object:

[source,typescript]
----
const state = {
  user: undefined,
  count: number
}
----

If most properties in the object can be inferred, it would be unnecessarily verbose to annotate it as such:

[source,typescript]
----

const state: {
  user: User | undefined
  count: number
} = {
  user: undefined,
  count: number
}
----

To save yourself from excessive boilerplate, you can annotate the `user` property with the assertion operator (`as`):

[source,typescript]
----
const state = {
  user: undefined as undefined | User,
  count: number
}
----

This tells TypeScript to infer `user` as `undefined | User`, instead of just `undefined`. You can also use it as an alternative to the type annotation separator (`:`):

[source,typescript]
----
let user: undefined | User = undefined
// is equivalent to:
let user = undefined as undefined | User
----

NOTE: that nothing happens with the value on the left side--neither at runtime nor during compile time. When a TypeScript file is compiled into JavaScript, the type annotations are stripped, and you get simply:

You can only use type assertion (`as`) if the value on the left side is a subset of the type on the right side. The following are valid:

[source,typescript]
----
// Correct ✅
const a = 1 as 1 | 2
const b = 100 as undefined | number
const c = undefined as undefined | number
----

But the following are incorrect:

[source,typescript]
----
// Incorrect ❌
const a = 1 as 2 | 3
const b = 100 as undefined | string
const c = null as undefined | number
----

=== Type Assertions with `unknown`

There is one exception to this rule: the `unknown` type. Even though the `unknown` type is the superset of all types, it can be asserted to any subtype. But this is mathematically incoherent, and it opens the door to a trick that lets you circumvent the type system: by asserting a type as `unknown`, you can then assert the unknown type as any other type without a type error:

[source,typescript]
----
const id = '123' as unknown as number
----

Now, TypeScript will consider `id` as a number, when it in fact is a string! In some niche cases, it can be useful to override the type checker when you are absolutely certain that you know better than TypeScript. But needless to say, once you do this, TypeScript will no longer be able to save you from runtime errors. Use `as` with great caution!

== Functions: Parametric Values (exponential types)

A function can be interpreted a parameterized value; that is, to construct the value, you need to provide a value for the parameter.

There are two ways to annotate a function. Either create a type alias for the function and annotate the identifier that contains the function:

[source,typescript]
----
type IsPositive = (value: number) => boolean
const isPositive: IsPositive = (value) => value > 0
----

Alternatively, annotate the parameters and the return type directly:

[source,typescript]
----
const isPositive = (value: number) => value > 0
----

== Generics: Parametric Types

Similarly to the relationships between values and functions, a type can be parameterized with a _type parameter_. That is, to construct the type, we first need to provide a type for the parameter.

If the syntax for parameterized types and types was consistent with the syntax for values and functions, we _would_ write it as such:

[source,typescript]
----
// Incorrect!
type Pair = <T> => [T, T]
----

Instead, we write

[source,typescript]
----
type Pair<T> = [T, T]
----

`Pair` is a sort of function that takes one type as an argument and returns a new type that is contructed from the type parameter.

If we want to annotate a value with this generic, we first need to construct a type from it by passing a type as an argument

[source,typescript]
----
type PairOfStrings = Pair<string>
const couple: Pair<string> = ['Sissi', 'Franz Joseph']
----

The type parameter is just a type as any other, and we can arbitrarily construct new types with it.

[source,typescript]
----
type HttpOkResult<T> = {
  statusCode: 200,
  body: T
}
const storyResult: HttpOkResult<{ content: unknown }> = {
  statusCode: 200,
  body: {
    content: {
      title: 'hello',
      text: 'Hello my friend...',
    }
  }
}
----

=== Generic Discriminated Unions

Generics (parametric types) in especially handy when combined with records and unions. With these three constructs, we can model any kind of data.

Let's revisit the tagged unions that we defined earlier where we defined this discriminated union:

[source,typescript]
----
type Ok = {
  tag: 'success'
  data: string
}

type Err = {
  tag: 'failure'
  error: Error
}

type OkOrFailure = Ok | Err
----

Wouldn't it be great if the `data` property was not bound to a specific type. If it was parameterized with a type parameter, we could re-use the `Result` type for different kinds of data:

[source,typescript]
----
type Ok<T> = {
  tag: 'ok',
  data: T
}
type Err = {
  tag: 'error',
  error: Error
}
type Result<T> = Ok<T> | Err
----

This can be used as in the example:

[source,typescript]
----
const okResult: Result<number> = {
  tag: 'ok',
  data: 1123,
}
const errorResult: Result<number> = {
  tag: 'error',
  error: new Error('Kaboom!'),
}
----

If we want, we can parameterize `Result` with two type parameters:

[source,typescript]
----
type Result<Data, Err> = Ok<Data> | Err<Err>
type OkResult<T> = {
  tag: 'ok',
  data: T
}
type ErrorResult<E> = {
  tag: 'error',
  error: E
}
----

For convenience, we could let the `Error` parameter default to type `Error`

[source,typescript]
----
type Result<Data, Err> = Ok<Data> | Err<Err>
----

=== Generic Function Types

Generics can be used to construct any kind of type; for example functions:

[source,typescript]
----
type Defer<T> = (value: T) => Promise<T>
----

Here `Defer<T>` is a function that wraps an argument in a promise. The argument can be any type, for example:

[source,typescript]
----
type DeferString = Defer<string>
const deferString: Defer<string> = (payload) => Promise.resolve(payload)
----

But what if we want to have the same function for other types? With `Defer`, we would have to write:

[source,typescript]
----
const deferBoolean: Defer<boolean> = (payload) => Promise.resolve(payload)
const deferNumber: Defer<number> = (payload) => Promise.resolve(payload)
----

The implementation is the same, so we shouldn't have to define multiple functions. The function body wraps the argument in a _container_, but it does not make any assumption of the content of that container. Therefore, we should be able to parameterize the type of the argument.

Here's another example:

[source,typescript]
----
type ReverseArray<T> = (items: T[]) => T[]
const reverseNumbers: ReverseArray<number> = (items) => items.reverse()
----

What if we try this:

[source,typescript]
----
// Incorrect
const reverseNumbers: ReverseArray<T> = (items) => Promise.resolve(items)
----

Unfortunately, this does not work in TypeScript because TypeScript will interpret `T` as a concrete type--not as a type argument. Inconveniently, for generic functions, we need to inline the type argument in the function expression:

[source,typescript]
----
const reverse = <T>(items: T[]) => items.reverse()
----

which has the intended effect:

[source,typescript]
----
const reversedAlphabet = reverse(['a', 'b', 'c', 'd', 'e', 'f'])
const reversedDigits = reverse([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
----

== TODOs

Topics that were not covered in this chapter, but which I indtend to include in the future:

* `typeof` type operator
* `keyof` type operator
* `extends` type constraint
* `[]` type operator
* `as const`
* `satisfies`

== Appendix

=== Pure Functions

A pure function is a function that always returns the same value given the same arguments.

Pure function always includes the following in its type signature

* the conditions for executing in the parameters
* the results in the return type

For example, the following pure function can always run given the listed arguments, and always has the same result:

[source,typescript]
----
const scale = (value: number) => 2
----

However, neither of these functions are pure

[source,typescript]
----
// Can return different values even if the arguments are identical
const scale = (value: number) => value * Math.random()
// The effects from console.log() are not embedded in the return value. There is no guarantee that it
const scale = (value: number) => {
  console.log('hello')
  return value * 10
}
----

Only pure functions can fully utilize the type system to generate correct code. Non-pure functions receive fewer guarantees from the type system.


=== `@ts-ignore`

A strongly typed language like TypeScript has the capability to analyze a program and prove whether it is correct, but it cannot do the opposite--that is, to prove whether a program is _incorrect_.

NOTE: A type error only indicates that the compiler cannot guarantee the program's correctness——it can still be functioning correctly even with type errors.

However good the TypeScript compiler is to reason about your code, there will arise scenarios where the programmer knows better than the type checker and thus want to override the type checker's decision. In these cases, you can use the `@ts-ignore` directive to tell TypeScript to ignore the type error:

.A function that takes a list of strings and returns a record that maps the index of the string to the string itself.
[source,typescript]
----
export const calculateZIndices = <const Keys extends string[]>(
  keys: Keys,
): { [key in Keys[number]]: number } =>
  // @ts-ignore
  Object.fromEntries(keys.map((key, index) => [key, index]))
----

This avoids the following error:

----
TS2322: Type { [k: string]: number; } is not assignable to type { [key in Keys[number]]: number;
----

Which, if you look closely at the code, is actually an inaccurate error message.

However, this feature should be used with great caution. It not only forces you to outperform TypeScript in your analysis of the program, but it can severely compromise the maintainability of the code.

CAUTION: A good rule of thumb is to never use `@ts-ignore`.

TIP: Whenever you _do_ use `@ts-ignore``, ensure that you test the code thoroughly with automated tests.
