== What You Will Learn

- You will get started with programming.
- JavaScript and TypeScript
- A tiny bit of HTML and CSS--just to get the JavaScript to run.
- Linear algebra--yes, you will need to learn some maths, but it will not be very complicated. In game programming, you will be limited by your knowledge in linear algebra, but to get started, you don't need to know a lot.
- Classical mechanics (physics)--you will learn some basic stuff about the motion of physical motions. If you have prior knowledge, that'll be beneficial when you go on to code on your own.

=== What _Not_ to Expect

- A comprehensive explanation of the JavaScript programming language
- Comprehensive documentation of various JavaScript library, such as the DOM.

== What you will need

To read this book, you don't need any programming experience. The goal is to learn programming while having fun, and what better way to achieve that by developing games?

This book is divided into several parts. For the first part, all you need is a computer with a web browser.

For the following parts, you will need to install some software. This book will help you with that, but you need to ensure that you have administrator rights and access to the internet.

== How to Read This Book

- Play around with your own examples--don't read the book from cover to cover.
- Write all code by hand--resist the temptation of copy-pasting the code. Part of the skill of programming is to type the things on the keyboard. If you copy and paste code from the internet (like from this book), you will miss out on a lot of details. Even though you will run into errors when you mistype something yourself, these events will develop your programming skills.
- Read the documentation. As a beginner, it's hard to learn everything at once. It's especially difficult to understand technical documentation that was written for experienced programmers. Nevertheless, it is an important skill to master. Furthermore, this book is not extensive enough to teach all the different methods and techniques--that is impossible. Go out and search for information yourself. here are some resources where you can look first:
  - Chat bots (https://chat.openai.com/[such as ChatGPT])
  - https://www.w3schools.com/[W3Schools]
